### ISSUE TITLE
Can't add token for private repos

### ISSUE THREAD

**Issue by tleunen** [codecov/sourcegraph-codecov#11]
The only option available in the sourcegraph menu is to go to the codecov documentation. How can I set the token for private repos?

![image](https://user-images.githubusercontent.com/1972567/48367918-3093e000-e680-11e8-8434-9961df01ff68.png)

**Comment by nickpresta** [comment]
Getting the same issue. I get the full list of options, including adding a private token, when viewing the command pallette on a public repo page but not when viewing my private repos.

**Comment by karkum** [comment]
Same issue here. Any update on this?

**Comment by sqs** [comment]
Not yet, sorry. I’ll follow up later tonight.

**Comment by sqs** [comment]
I believe we’ve identified the issue. We plan to fix it Friday night or Saturday morning (~32 hours from now).

**Comment by sqs** [comment]
Please try it now. As it turns out, I believe it would have appeared if you were on a code file page on GitHub. It now always appears, and if you are not on a code file, it tells you to visit a code file and re-try. This should unblock you and avoid confusion for future users.

(Of course, we're working on making it able to work fully on other GitHub pages, such as repository and directory pages on GitHub.)
